version: "3.8"

services:
  react-nginx-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:80
    environment:
      - CHOKIDAR_USEPOLLING=true