// Generates supabase/seed.sql from the content checked in under src/data.
// Usage: node scripts/seed.mts
import { readFileSync, writeFileSync } from 'node:fs';

import contact from '../src/data/contact.ts';
import projects from '../src/data/projects.ts';
import courses from '../src/data/resume/courses.ts';
import degrees from '../src/data/resume/degrees.ts';
import positions from '../src/data/resume/positions.ts';
import { skills } from '../src/data/resume/skills.ts';
import stats from '../src/data/stats/personal.ts';

const about = { markdown: readFileSync('src/data/about.md', 'utf8') };

const sections: Record<string, unknown> = {
  about, positions, degrees, courses, skills, projects, contact, stats,
};

const rows = Object.entries(sections).map(([key, data]) => (
  `insert into public.site_content (key, data) values ('${key}', $seed$${JSON.stringify(data)}$seed$::jsonb)\n`
  + 'on conflict (key) do nothing;'
));

writeFileSync(
  'supabase/seed.sql',
  `-- Initial site content, generated by scripts/seed.mts. Existing rows are never overwritten.\n${rows.join('\n\n')}\n`,
);
console.log(`wrote ${rows.length} sections`);
